### ISSUE TITLE
Hide XXHash symbols

### ISSUE THREAD

**Issue by zirconium-n** [gyscos/zstd-rs#105]
Current implemetation does not hide xxhash symbols which would cause duplicate symbol in certain cases. 

It would be nice to inline xxhash related symbols. 

Something similiar to the following would do
```
glob = ["zstd/lib/common/[!xxhash]*.c", /* ... */ ]   // exclude xxhash.c
config.define("XXH_PRIVATE_API", Some(""));
```

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Latest commit should include that. Tell us if this suits your needs! :)

**Comment by gyscos** [comment]
Closing for now, feel free to re-open if needed.
