### ISSUE TITLE
Move experimental flag to feature in zstd-rs build

### ISSUE THREAD

**Issue by stoneeric** [gyscos/zstd-rs#107]
Hello,

Currently, zstd-rs pulls in zstd-safe with the experimental feature included by default [here](https://github.com/gyscos/zstd-rs/blob/91d87400a15ce4ea7b97e776fbe8ab6971557c9d/Cargo.toml#L19).

I'd like to request to have this moved to a feature so it can be disabled when zstd-rs is pulled in as a dependency. I can provide a PR for this if needed.

Reasoning: one of the considerations around adding zstd-rs to Fuchsia is that it's undesirable to pull in another copy of zstd (as part of zstd-sys). This leads to a need to generate bindings against a different copy of zstd which may or may not match what zstd-safe is constructed to expect. There's a greater chance of a breaking mismatch occurring with experimental (unstable) APIs enabled.

The more general problem is support for the "bring your own zstd" use case, so other solutions targeting that could work for this as well. I'd imagine that'll be significantly more difficult to solve though.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

I should have added that in the latest commit. A few functions were moved behind this experimental flag (mostly toggling "magic bytes", and creating dictionaries by reference). Does this suit your needs?

**Comment by stoneeric** [comment]
Yep, looks good. Thank you!
