### ISSUE TITLE
Confirm Send is safe for CCtx

### ISSUE THREAD

**Issue by stoneeric** [gyscos/zstd-rs#112]
In zstd-safe, the compression context implements Send:

https://github.com/gyscos/zstd-rs/blob/cd0450d78c26081769713d4aa645a819cd282b5d/zstd-safe/src/lib.rs#L550

[Zstd documentation](http://facebook.github.io/zstd/zstd_manual.html) notes the following about the compression context:

>   Note 2 : In multi-threaded environments,
>          use one different context per thread for parallel execution.

Since the upstream documentation isn't very clear about this, we'd like to confirm that Send is safe to implement

**Comment by gyscos** [comment]
The `Send` trait was added by https://github.com/gyscos/zstd-rs/pull/32, approved by @Cyan4973.

**Comment by stoneeric** [comment]
Awesome, thanks!
