### ISSUE TITLE
Add window size setting?

### ISSUE THREAD

**Issue by jguhlin** [gyscos/zstd-rs#121]
Hello, is it possible to add the zstd window size / buffer setting to this API? 

I can try a pull request but not familiar with the underlying zstd . I believe it is this: ZSTD_c_windowLog ?

Cheers,
--Joseph

**Comment by gyscos** [comment]
Hi!
I just exposed this `window_log` parameter (as well as any `zstd_safe::CParameter`) on the encoders.

I also added the same for decoders.

**Comment by gyscos** [comment]
Should be published with zstd 0.8.2.
