### ISSUE TITLE
0.8.2 fails async-compression crate tests,  0.8.1 is fine

### ISSUE THREAD

**Issue by ahornby** [gyscos/zstd-rs#122]
I've tried updating async-compression to zstd 1.5.0 in https://github.com/ahornby/async-compression/tree/zstd_1.5.x, but I see test failures when it picks up zstd 0.8.2. If I force it 0.8.1 it works

Reproduces with
~/local/async-compression$ cargo test --features zstd,tokio zstd

I don't know if this is an async-compression or zstd-rs issue, raising it in both places just in case.

**Comment by gyscos** [comment]
Thanks for the report!

0.8.2 includes a change that runs an extra "empty" step of the encoder/decoder in case the previous run didn't flush everything. It passes the local (non-async) tests, but it's not impossible that I missed some other edge cases. Will have a look.

**Comment by gyscos** [comment]
Hmm actually it doesn't _look_ like it should be impacted: the failing tests are `zstd::tokio::write::decompress::long` and `zstd::tokio::write::decompress::long_chunks`, none of them use look like they use the `Reader` that we changed. :^S

**Comment by Nemo157** [comment]
It appears that while decoding `Status::remaining` is 0 when there are still 9 bytes left in the input to write. It could be that the [check for end-of-frame here in `async-compression`](https://github.com/Nemo157/async-compression/blob/pr%C4%ABmum/src/codec/zstd/decoder.rs#L36) is wrong, but my impression from https://github.com/gyscos/zstd-rs/issues/78 was that this was a valid way to detect it.

**Comment by gyscos** [comment]
Looks like the compressed data, compressed using zstd's read-encoder, contains 2 frames now. I suppose the reader only reads one of the two frames.
It's very possible that the reader changes made it output 2 frames now by mistake.

**Comment by gyscos** [comment]
Ok I found the issue: it happened when flushing the operation was filling the output buffer and had to be done again - the recent change was messing this up. Should now be fixed, will push a release shortly.
