### ISSUE TITLE
Non vendored zstd

### ISSUE THREAD

**Issue by otavio** [gyscos/zstd-rs#124]
We'd like to use this on embedded devices but we'd like to link to the `zstd` dynamic library. I couldn't find how to do it. Is it possible?

**Comment by gyscos** [comment]
Hi!

I didn't try it myself, but there is a `pkg-config` feature for `zstd-sys`, which may give you more freedom regarding the `libzstd` library we link against. I'm not 100% sure it lets you use dynamic linking (but https://github.com/gyscos/zstd-rs/issues/88 seems to suggest it does). Did you try that?

**Comment by otavio** [comment]
Ohh, cool. I'll give it a try.
