### ISSUE TITLE
Cargo build fails with os error 1

### ISSUE THREAD

**Issue by Jakub-Wilk** [gyscos/zstd-rs#126]
`cargo build` output with `RUST_BACKTRACE=full`
https://pastebin.com/MrCs2RGQ

Cargo.toml:
```
[dependencies]
actix-web = "4.0.0-beta.8"
actix-session = "0.5.0-beta.2"
dotenv = "0.15.0"
mongodb = "2.0.0-beta.2"
tera = "1.12.1"
serde = "1.0.126"
rand = "0.8.4"
```

System:
```
OS: 5.4.72-microsoft-standard-WSL2
Cargo: cargo 1.53.0
Rust: rustc 1.53.0
```

Everything in the current directory and in ~/.cargo has permissions 777

**Comment by gyscos** [comment]
```
                                 at /home/wolfiewsl/.cargo/registry/src/github.com-1ecc6299db9ec823/zstd-sys-1.5.0+zstd.1.4.9/build.rs:165:5
    18:     0x56247d847a9d - build_script_build::main::hc3e7900a8faf7855
```

The corresponding code is:

```rust
fs::copy( 
    src.join("dictBuilder").join("zdict.h"),
    include.join("zdict.h"), 
) 
```

It tries to copy the header file from `$PWD/zstd/lib/dictBuilder/zdict.h` to `${OUT_DIR}/include/`. The weird thing is that the line above, where it copies `zstd/lib/common/zstd_errors.h` to the same location, apparently worked fine.

If you clone this repo and try just building zstd-sys, does it work?

(Note that this is using a sligtly older version of `zstd-sys`, I am curious if the errors also happens with a more recent version. Though the part that copies the header files is not changed.)

**Comment by Jakub-Wilk** [comment]
Building `zstd-sys` from this repo works fine

**Comment by Jakub-Wilk** [comment]
I decided to try compiling the original crate again and it this time it compiled with no issue? I have no idea why and how, because I tried restarting WSL before and it didn't work, but this time it did. I guess I'll close it, weird.
