### ISSUE TITLE
Can't create AutoFinishEncoder

### ISSUE THREAD

**Issue by marcospb19** [gyscos/zstd-rs#129]
I was reading the docs, and I cannot create [`zstd::stream::write::AutoFinishEncoder`](https://docs.rs/zstd/0.9.0+zstd.1.5.0/zstd/stream/write/struct.AutoFinishEncoder.html).

The `new` method is private, is this intended? (maybe I'm missing something)

**Comment by marcospb19** [comment]
For some reference, I need to add this stream to https://github.com/ouch-org/ouch/blob/master/src/commands.rs#L195-L208 in order to make the `ouch` cli tool support `zstd`, as requested in one of the issues.

However, I'm using `Box<Write>`, so I cannot call `.finish()`, unless I wrap the encoders into some enum, or try using `std::any::Any`.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The usual way is to call `auto_finish` on a regular encoder (I should probably point there on the auto-finish encoder doc page...).

**Comment by marcospb19** [comment]
Oh, thanks! I will make an PR pointing this out :slightly_smiling_face: .

**Comment by marcospb19** [comment]
I added some links inspired by how it's done in [the std](https://doc.rust-lang.org/nightly/std/iter/struct.Enumerate.html).

Thanks for the lib!
