### ISSUE TITLE
`include_contentsize` is not working

### ISSUE THREAD

**Issue by shenek** [gyscos/zstd-rs#137]
I may be wrong, but using following code
```rust
fn main() -> std::io::Result<()> {
    let args = std::env::args().collect::<Vec<_>>();
    let source = &args[1];
    let destination = &args[2];

    let mut fsrc = std::fs::File::open(source)?;
    let fdst = std::fs::File::create(destination)?;

    let mut encoder = zstd::stream::Encoder::new(fdst, 0)?;
    encoder.include_contentsize(true)?;
    std::io::copy(&mut fsrc, &mut encoder)?;
    encoder.finish()?;

    Ok(())
}
```
doesn't produce output file with stored content size.
```sh
$ zstd -l example.txt.zst
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
     1      0     0.02 KB                        None  example.txt.zst
```
While `zstd` command 
```sh
$ zstd example.txt
```
works as expected
```sh
$ zstd -l example.txt.zst
Frames  Skips  Compressed  Uncompressed  Ratio  Check  Filename
     1      0     0.03 KB       0.01 KB  0.536  XXH64  example.txt.zst
```

According to RFC the header (where original size is present) is written few bytes after start.
see https://datatracker.ietf.org/doc/html/rfc8878#section-3.1.1

So in the stream mode. It would be necessary to "rewind" output stream back to start to write the original size to header.
And that doesn't make much sense. Especially for large files. So either there is some bug in the implementation or it doesn't make sense to sense to use `include_contentsize` function and it might be deleted, because it is useless.

Or I misinterpreted what `include_contentsize` should do.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Writing the content size is already the default, so `encoder.include_contentsize(true)` should not have any effect.

As you mentioned though it's not possible when the content size is not known. This is currently only possible by "pledging" the size ahead of time, using [`set_pledged_src_size`](https://docs.rs/zstd-safe/latest/zstd_safe/struct.CCtx.html#method.set_pledged_src_size) from `zstd-safe`. I realize now that this has not been made available in the high-level `zstd` crate, woops!

**Comment by shenek** [comment]
Super. `set_pledged_src_size` works perfectly. Thanks.
