### ISSUE TITLE
Runtime & build error: missing symbol `ZDICT_trainFromBuffer`

### ISSUE THREAD

**Issue by jrobhoward** [gyscos/zstd-rs#144]
FYI: After semver updated my `zstd-sys` dependency to `1.6.4+zstd.1.5.2`, I started getting a runtime error on Linux and a build error on macOS & Windows.

e.g.

```
OpenLibrary failed: Could not load 'lib/libx.so.2'.  lib/libx.so.2: undefined symbol: ZDICT_trainFromBuffer
```

or

```
[2022-03-09T19:32:40.140Z]          liblibrocksdb_sys-cfbd66db62f83f79.rlib(block_based_table_builder.o) : error LNK2019: unresolved external symbol ZDICT_trainFromBuffer referenced in function "private: void __cdecl rocksdb::BlockBasedTableBuilder::EnterUnbuffered(void)"
```

Adding the following to my `Cargo.toml` functions as a workaround:
```
zstd-sys = "=1.6.3+zstd.1.5.2"
```

**Comment by gyscos** [comment]
Argh right that got moved behind a feature, and [rocksDB is using default-features=false](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/Cargo.toml#L28). Looks like this needs a new version then.

**Comment by jrobhoward** [comment]
The builds are working again after `1.6.4+zstd.1.5.2` was yanked.  Thanks for the quick response!
