### ISSUE TITLE
Consider adding an environment variable for dynamic linking

### ISSUE THREAD

**Issue by happysalada** [gyscos/zstd-rs#150]
Would you be ok with an environment variable that could be used to specify dynamic linking ?
At the moment dynamic linking relies on the "pkg-config" feature.
having the condition include also an environment variable would 
- make it easy to use dynamic linking in a dev environment (even for dependencies of dependencies). It could save precious compile time
- Make it easy for some linux distributions to avoid static compilation and rely on dynamic linking (where static compilation fails for some reason, you could rely on a pre-built version, (one example of this is nixos).

if you are ok with this, I would be happy to make a PR.
how about the name CARGO_ZSTD_SYS_DYNAMIC_LINKING for the environment variable ?

Last but not least, thanks a lot for the great library!

**Comment by Artturin** [comment]
another dev from nixpkgs who came to find if there was a way to not need to [patch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/nushell/use-system-zstd-lib.diff) nushell to make it's dependency use pkg-config checking in :)
