### ISSUE TITLE
Is the following supported?

### ISSUE THREAD

**Issue by firasuke** [gyscos/zstd-rs#156]
Is it possible to do the following `zstd -22 --ultra --long=31 -T0`  using `zstd-rs`?

**Comment by gyscos** [comment]
Hi, and thanks for the question!

* `zstd` defaults to compressing; for example, if you want a `Write` that can compress, you can use the [`Encoder`](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html).
* `-22` is done by just specifying the level, for example [`Encoder::new(writer, 22)`].(https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.new).
* `--ultra` just enables levels 20+ on the CLI, it's not needed in the library.
* `--long=31` is done by [enabling long-distance matching](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.long_distance_matching), and [specifying the window log](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.window_log).
* `-T0` means "use as many threads as CPUs". You can [specify the number of threads](https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.multithread); detecting the number of CPUs is not provided by the library, but you can use something like [num_cpus](https://crates.io/crates/num_cpus).

**Comment by firasuke** [comment]
Thanks for the thorough explanation!

I still didn't quite understand how `--long=31` should be specified using the library, here's what I wrote:

```Rust
    let tar_zst = fs::File::create("archive.tar.zst");
    let buf = io::BufWriter::new(tar_zst);
    let zstd = Encoder::new(buf, 22)?;
    let mut ar = tar::Builder::new(zstd);
    zstd.finish()?;
```

**Comment by gyscos** [comment]
```rust
     let tar_zst = fs::File::create("archive.tar.zst");
     let buf = io::BufWriter::new(tar_zst);
     let mut zstd = Encoder::new(buf, 22)?;
     zstd.multithread(8)?; // hardcode 8 threads here, or use num_cpus
     zstd.long_distance_matching(true)?;
     zstd.window_log(31)?;
     let mut ar = tar::Builder::new(zstd);
     zstd.finish()?;
```

**Comment by firasuke** [comment]
Thanks for the amazing help and for the quick reply!

Got one last question, would it be wise to use `AutoFinishEncoder` in place of `Encoder` and remove `zstd.finish()?` alltogether, so that it becomes:

```Rust
     let tar_zst = fs::File::create("archive.tar.zst");
     let buf = io::BufWriter::new(tar_zst);
     let mut zstd = AutoFinishEncoder::new(buf, 22)?;
     zstd.multithread(8)?; // hardcode 8 threads here, or use num_cpus
     zstd.long_distance_matching(true)?;
     zstd.window_log(31)?; // You'll need to do this too on the Decoder when decompressing.
     let mut ar = tar::Builder::new(zstd);
```

**Comment by gyscos** [comment]
It's possible indeed, and can simplify integration with the tar builder. Note though that you give up error reporting during the finish phase; if something fails here, the default implementation panics, which may not be acceptable for all use cases

**Comment by firasuke** [comment]
Thanks a lot! Closing now..
