### ISSUE TITLE
Fails building in windows 10

### ISSUE THREAD

**Issue by ricardomatias** [gyscos/zstd-rs#160]
Before it showed a similar message about gcc, which I installed, but now it's asking for `ar`, which I don't know where to get. Help is appreciated.

```
Compiling zstd-sys v2.0.1+zstd.1.5.2
error: failed to run custom build command for `zstd-sys v2.0.1+zstd.1.5.2`  
...
error occurred: Failed to find tool. Is `ar` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)
```

**Comment by gyscos** [comment]
I'll admin not knowing much about rust installations on windows to be honest.

It looks like you have the GNU version (as opposed to MSVC). I guess you used something like mingw-w64 or cygwin to install that? Would either of them provide a `ar` or `binutils` package?

**Comment by ricardomatias** [comment]
yeah, the problem is that in most places it is not mentioned that you should install some libraries with Visual Studio's help. For future reference, [here](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup) is all the information to have a proper rust dev environment on windows.
