### ISSUE TITLE
Offer alternative API's similar to flate2

### ISSUE THREAD

**Issue by kallisti5** [gyscos/zstd-rs#164]
It's pretty common to support multiple compression algorithms within applications.  zstd and zlib are pretty common partners.

flate2 offers a BufReader API, it would be nice (tm) if zstd offered a similar function.

https://docs.rs/zstd/latest/zstd/stream/zio/struct.Reader.html
vs
https://doc.servo.org/flate2/zlib/read/struct.ZlibDecoder.html

Example:
```rust
    fn inflate_heap_chunk(&mut self, index: u64) -> Result<usize, Box<dyn error::Error>> {
        let pos = self.heap_chunk_offset(index)?;
        let uncompressed_size = self.heap_chunk_uncompressed_size(index)? as usize;
        let header = self.header.as_ref().unwrap();
        let filename = self.filename.as_ref().unwrap();
        println!("Chunk {}; {} - {} inflate to {}", index, pos, pos + header.heap_chunk_size as u64,
            uncompressed_size);     
        
        let mut f = File::open(filename)?;
        f.seek(SeekFrom::Start(pos))?;           
        let mut buffer = vec![0; uncompressed_size];
        let mut reader: Box<dyn Read> = match header.heap_compression {
            0 => Box::new(f),
            1 => Box::new(ZlibDecoder::new(f)),
            2 => Box::new(zstd::stream::zio::Reader::new(f)),      //// This won't work since I also need an operation.
            _ => return Err(From::from(format!("Unknown hpkg heap compression: {}", header.heap_compression)))
        };

        reader.read_exact(&mut buffer)?;         
        self.heap_data.push(buffer);
        Ok(uncompressed_size)
    }
```

**Comment by kallisti5** [comment]
It's also completely possible i'm missing something in calling zio::Reader.  There aren't any examples so i'm not 100% sure what the intent of ```Operation``` is

**Comment by gyscos** [comment]
Do you just want a `Read` implementation that decodes? The [`Decoder`](https://docs.rs/zstd/latest/zstd/stream/read/struct.Decoder.html) (linked from the crate's top-level doc page) should be what you need.

**Comment by gyscos** [comment]
There's also a couple [`examples`](https://github.com/gyscos/zstd-rs/blob/master/examples), for example [this one](https://github.com/gyscos/zstd-rs/blob/master/examples/zstd.rs#L38-L49) using this `Decoder`.
