### ISSUE TITLE
Expose `flush` operation

### ISSUE THREAD

**Issue by piegamesde** [gyscos/zstd-rs#165]
I need to be able to "flush" the zstd stream, so that all previously compressed bytes are guaranteed to be decompressed on the other side. AFAICT, the only place where this functionality is exposed is `zstd::stream::raw::Operation::flush`, while none of the higher wrappers provide it. This means that since I depend on this feature, I am forced to use the raw API even though one of the other ones would generally suit me better.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

The writers should have a flush method (as part of the `Write` trait). Does this work for you?

**Comment by piegamesde** [comment]
Yes, this should work for me, thanks. What about the `Read` interfaces though?

**Comment by gyscos** [comment]
The decoder should never need to flush anyway, so indeed it leaves the `Read` encoder, where flushing is more rarely required.
In that case there's unfortunately no clean way to add it to the API.

We could:
* Add a `fn flush(&mut self, out: &mut [u8]) -> Result<usize>` that would directly write to `out` any result from such "flushing", bypassing the usual `Read` interface for this.
* Add a `fn flush_on_next_read(&mut self)` and a matching boolean flag to the encoder. Might not be such a problem to be honest.

Is that what you would be looking for?

**Comment by piegamesde** [comment]
I don't like `flush_on_next_read`, because it is stateful and also because the "next read" is weirdly defined in the presence of provided methods like `read_all`. A `flush` method that actively reads bytes would be better in that regard. I'd be fine with a variant that simply returns `Result<Vec<u8>>` too.

Another option would be to have `flush` return a struct that is `Read` again, like in the `take` API.

**Comment by gyscos** [comment]
I just added a `flush(&mut self, out: &mut [u8]) -> io::Result<usize>` to `zstd::stream::read::Encoder`, please tell me if that fits your use-case.

Though I'm curious in which situation you would use it. _Usually_ you need to flush when using the `write::Encoder`, since that's where you have more control on the input you feed the encoder.

**Comment by piegamesde** [comment]
Not tested but the diff looks fine for me, thank you.

My use case is that I have an input stream that I'm putting into compressed chunks of a certain size, and every X chunks I have a flush barrier to ensure that all previously sent data can be accessed.

**Comment by gyscos** [comment]
I'll close the ticket as the solution described above has now been deployed.
Feel free to re-open if it doesn't fully fit your needs.
