### ISSUE TITLE
zstd-sys build script shouldn't hard-code `opt_level(3)`

### ISSUE THREAD

**Issue by jfirebaugh** [gyscos/zstd-rs#166]
Please remove this line:

https://github.com/gyscos/zstd-rs/blob/6fe67d6ac878a07cf2fddbf06c8c3b83615b2848/zstd-safe/zstd-sys/build.rs#L132

This overrides a user's desired optimization level as specified by the cargo profile or other external source of configuration (for instance when built via rules_rust). See the [documentation for `opt_level`](https://docs.rs/cc/latest/cc/struct.Build.html#method.opt_level):

> This option is automatically scraped from the `OPT_LEVEL` environment variable by build scripts, so it’s not required to call this function.

Other references:

* https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts (search for `OPT_LEVEL`)
* https://github.com/bazelbuild/rules_rust/blob/0fc834bdfa9df75c6ffdcadb5d1bb9fc43cc247b/cargo/cargo_build_script.bzl#L109

**Comment by gyscos** [comment]
Sure!

I think I only added this option because I was copying the rules from zstd's Makefile, but leaving it up to the build script makes sense.
