### ISSUE TITLE
types of macro defined constants

### ISSUE THREAD

**Issue by guoci** [gyscos/zstd-rs#169]
Why are the types of `ZSTD_CONTENTSIZE_UNKNOWN` and  `ZSTD_CONTENTSIZE_ERROR` in rust is `i32` but in the C header file are defined as `unsigned long long int`?

https://docs.rs/zstd-sys/2.0.1+zstd.1.5.2/src/zstd_sys/bindings_zstd_experimental.rs.html#49-50
https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L180-L181

**Comment by gyscos** [comment]
These bindings are auto-generated, so it seems to be what `bindgen` comes up with.

Note that `zstd_safe` re-exports this variable with the proper type: https://docs.rs/zstd-safe/latest/src/zstd_safe/constants.rs.html#6
