### ISSUE TITLE
`Encoder` doesn't flush its underlying writer when it itself is being flushed

### ISSUE THREAD

**Issue by heinrich5991** [gyscos/zstd-rs#170]
Use case: Writing binary data to stdout using `zstd::Encoder::new(io::stdout().lock(), 0)?.auto_finish()`.

`io::stdout().lock()` is unfortunately line-buffered so it needs an extra `flush` call to actually write out the data. Calling `flush` on the zstd encoder doesn't flush the underlying buffer.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed it seems that this was missed. I just [pushed a commit](https://github.com/gyscos/zstd-rs/commit/5bca33ce0032b416af0755ed6bb4bc633a3420b9) that should fix that. Does it work for you?

**Comment by heinrich5991** [comment]
I was about to open a pull request with basically the same content. Yes, that fixes it for me.

**Comment by heinrich5991** [comment]
https://github.com/heinrich5991/zstd-rs/commit/3a6007c515467850811b3818bb1ec4596a05cbde

**Comment by heinrich5991** [comment]
Fixed by 5bca33ce0032b416af0755ed6bb4bc633a3420b9.
