### ISSUE TITLE
Mention 3-clause BSD in `zstd-safe/zstd-sys/LICENSE`?

### ISSUE THREAD

**Issue by martinvonz** [gyscos/zstd-rs#171]
https://github.com/gyscos/zstd-rs/blob/master/zstd-safe/zstd-sys/src/bindings_zdict.rs includes the 3-clause BSD license, so doesn't that mean that it needs to be mentioned in `zstd-sys`'s LICENSE file?

**Comment by martinvonz** [comment]
I guess that applies to all of the generated bindings, actually.

**Comment by martinvonz** [comment]
I can create a PR for that if it helps. I think licenses are usually concatenated (with some separator between) in the LICENSE file. Would you like the BSD license in the main LICENSE file or in a separate file?

**Comment by gyscos** [comment]
Hi!
Sorry, didn't get much time to look into that.

> I can create a PR for that if it helps.

Absolutely! Thanks a lot :)
