### ISSUE TITLE
`flush` not implemented for `zstd::stream::raw::Decoder`

### ISSUE THREAD

**Issue by pkolaczk** [gyscos/zstd-rs#184]
`flush` called on `Decoder` always returns `Ok(0)` and does *not* flush the stream.

Any plans to implement it?

**Comment by gyscos** [comment]
Hi, and thanks for the report!

Indeed, while the underlying zstd library does not offer a separate flush mechanism, we can effectively flush by running an extra step with an empty input. Note that we cannot get an accurate estimation of remaining buffer in this case, so we just return either 0 (we know there's nothing left) or 1 (there might still be _something_  there).

This should be available in the latest commit.

**Comment by pkolaczk** [comment]
Thank you! That would simplify a lot, as I could make some code generic for `Encoder` and `Decoder` by coding against the `Operation` trait.

**Comment by gyscos** [comment]
Published zstd 0.12.2 with this fix.
