### ISSUE TITLE
Support env `CC`, `CCFLAGS` and `LDFLAGS` and and use `RUSTC_WRAPPER` if it is `sccache`/`cacheopt`?

### ISSUE THREAD

**Issue by NobodyXu** [gyscos/zstd-rs#192]
zstd-sys use the system-wide c compiler and the pre-specified cflags without respecting env variables `CC`, `CCFLAGS` and `LDFLAGS`.

Also, if `RUSTC_WRAPPER` is `sccache` or `cacheopt`, then it's possible users want to use it to wrap over c compiler/linker too.

**Comment by gyscos** [comment]
I think `cc-rs` already supports `CC`, `CFLAGS` (I assume that's what you meant instead of `CCFLAGS`?) and `AR`. Not sure about `LDFLAGS`, but it looks like it would belong there as well?

**Comment by NobodyXu** [comment]
> I think `cc-rs` already supports `CC`, `CFLAGS` (I assume that's what you meant instead of `CCFLAGS`?) and `AR`. Not sure about `LDFLAGS`, but it looks like it would belong there as well? EDIT: looks like `cc-rs` doesn't run the linker, so no need for `LDFLAGS`. That'd be up to rustc itself, and I'm not entirely sure how to configure that.
> 
> As for `RUSTC_WRAPPER`, I don't really know how to inject that into `cc-rs`.

It seems that crate `cc` already handles all of them...

I bring this up because I saw this somewhere, but I just remember I saw this when contributing to the crate `cc`...
