### ISSUE TITLE
Feature gate pkg-config for wasm32-unknown-unknown

### ISSUE THREAD

**Issue by kylebarron** [gyscos/zstd-rs#205]
updating `zstd-sys` from 2.0.1 to 2.0.6 now brings in `pkg-config`. I'm not entirely sure why, but updating 2.0.1 to 2.0.6 causes wasm-pack to add
```js
imports['env'] = require('env');
```
at the beginning of the file, which crashes in various environments. See related issues like https://github.com/rustwasm/wasm-pack/issues/743, https://github.com/rustwasm/wasm-bindgen/issues/2215.

I don't know the details here but was able to track this down where it worked in Node with 2.0.1 and failed in Node with 2.0.6, using `cargo update --package zstd-sys` 🤷‍♂️

**Comment by ppodolsky** [comment]
I've also faced the similar issue, but it happened in debug builds only. I've disasmed WASM module and saw that in my case it embedded `malloc` and `free` (through ZSTD_customMalloc) which causes these `env` imports. 

Luckily, building with `thin` and `wasm` features helped me. At least, worth to try.

**Comment by ppodolsky** [comment]
Even if it is not your issue, you may try to disasm wasm module with [wabt](https://github.com/WebAssembly/wabt) and grep `import "env"`, something like
```bash
wasm2wat you_binary.wasm | grep import
```
Then grep found symbols the same way, it may hint you where these imports come from.

**Comment by REASY** [comment]
It seems related to the changes in optimization that caused the breakage https://github.com/gyscos/zstd-rs/issues/151#issuecomment-1465141286

**Comment by kylebarron** [comment]
Finally getting back to this. In https://github.com/kylebarron/parquet-wasm/pull/275 I can confirm that the issue happens between zstd-sys 2.0.1 and 2.0.3. Pinning to 2.0.3 brings in `import env`, while 2.0.1 does not.

This means that the root cause is _not_ `pkg-config` because 2.0.3 does not include `pkg-config`

**Comment by kylebarron** [comment]
Well it looks like passing `features = ["wasm", "thin"]` does actually solve my issue after all! It took me a while to realize that it's possible to pass the features on even though `zstd` is a transitive dependency. I can just declare `version = "*"` and have the version be pinned by my direct dependencies
