### ISSUE TITLE
Incorrect compression level range in zstd::stream::write::Encoder

### ISSUE THREAD

**Issue by ariel-miculas** [gyscos/zstd-rs#208]
In https://docs.rs/zstd/0.12.3+zstd.1.5.2/zstd/stream/write/struct.Encoder.html#method.new, shouldn't the compression level be in the range (1,22) instead of (1,21)? In zstd [1.5.1](http://facebook.github.io/zstd/zstd_manual.html) it says:
> The library supports regular compression levels from 1 up to ZSTD_maxCLevel(),
  which is currently 22

**Comment by gyscos** [comment]
Indeed, the comment appears incorrect (maybe outdated?).
