### ISSUE TITLE
Update downstream zstd to the latest version

### ISSUE THREAD

**Issue by ppodolsky** [gyscos/zstd-rs#213]
Hello! Firstly, thank you for all your efforts.

Probably you have seen [the issue](https://github.com/facebook/zstd/pull/3517) in zstd. Rather sever thing that could led to data corruption. Just letting you know, I believe it is worth to schedule the update if you are using higher compression levels

**Comment by gaby** [comment]
@gyscos Any plans to publish a new release?

**Comment by gyscos** [comment]
Zstd sys 2.0.8 was released with zstd 1.5.5.
