### ISSUE TITLE
Non-consuming version of finish() method?

### ISSUE THREAD

**Issue by sid0** [gyscos/zstd-rs#22]
Here's an interesting issue. I'm using zstd with [tokio-io](https://github.com/tokio-rs/tokio-io), which adds the notion of non-blocking writes signaled with `io::Error(io::ErrorKind::WouldBlock)`. Typically the bottom-most layer will need to be aware of the non-blocking nature of writes. Intermediate layers like `Encoder` can just pass the error message up and trust that higher layers will handle it.

However, with consuming methods like `finish()`, there's a wrinkle:

1. These methods cause writes to happen (a `flush()` before the `finish()` is insufficient because the `finish()` does a write of its own).
2. They will consume the encoder even if the error is a `WouldBlock` error (where the caller needs to retry the `finish()` after some time).

I'm really not sure how to handle this use case. A non-consuming version of `finish` would solve this issue but makes the API uglier :/

I'm also going to file an issue against tokio-io to talk about it there, because this seems like a general API deficiency.

**Comment by sid0** [comment]
One option might be to return `self` as part of the error case with `finish`.

**Comment by sid0** [comment]
Yeah, what Alex suggested in https://github.com/tokio-rs/tokio-io/issues/35 was one of two options:

1. Add a `try_finish` method which doesn't consume `self` and returns `io::Result<()>`.
2. Make `finish` return `Result<W, (Self, io::Error)>`.

**Comment by gyscos** [comment]
Ah, I always wanted to make this library work better with tokio, but never had the time to look into it - thanks for your help!
> 1. Add a `try_finish` method which doesn't consume self and returns `io::Result<()>`.
> 2. Make `finish` return `Result<W, (Self, io::Error)>`.

I'd like to keep the current `finish`, to minimize changes to the blocking IO style. I would then favor a new method like `try_finish`, though it could also have the signature proposed for `finish`.

I'm still a bit torn between those two solutions.
* I like the fact that after a successful `finish()`, the type system forbids writing more data, or `finish`ing the stream again. This would favor `try_finish(self) -> Result<W, (Self, io::Error)>`
* I feel like this would be a bit _too_ close to the current `finish` method, thus bringing some confusion.

**Comment by sid0** [comment]
OK, I'd be happy to add `try_finish(self) -> Result<W, (Self, io::Error)>`.

As a followup, how would you feel about me pulling in `tokio-io` as an optional dependency and adding first-class support for `AsyncWrite`? Currently I have to do https://gist.github.com/sid0/2afeda9cb29e7250acce9badcc9727eb locally, which I could skip if I did this in the crate directly.

One problem with that would be that `tokio-io` is currently unstable, so its API might change underneath this crates. That imposes an ongoing maintenance burden.

**Comment by gyscos** [comment]
Sounds good. Maybe make it optional behind a `tokio` feature?
