### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by corneliusroemer** [gyscos/zstd-rs#228]
Would be nice to release so that we can take advantage of the zstd improvements since 1.5.5, thanks!

**Comment by NobodyXu** [comment]
It is already released in zstd-sys https://docs.rs/zstd-sys/latest/zstd_sys/

**Comment by corneliusroemer** [comment]
Oh I see, so it's just the Github releaes that are lagging behind. Probably good to either fix and catch up or to disable github releases from being shown in the repo.

**Comment by NobodyXu** [comment]
@corneliusroemer Better to check https://docs.rs/zstd

Latest is actually zstd v0.12.3 and works with any zstd-sys >= v2.0.1

**Comment by z3cko** [comment]
Can you explain how zstd and zstd-sys are related? The version number "zstd v0.12.3+zstd.1.5.2" suggests that zstd 1.5.2 is used. Also, would it not make sense to update the version of zstd-safe in Cargo.toml of zstd-rs to v6.0.5+zstd.1.5.4?

**Comment by NobodyXu** [comment]
> Can you explain how zstd and zstd-sys are related?

zstd uses zstd-safe, which depends on zstd-sys.

zstd-sys contains the build.rs that build and linked with zstd library, its lib.rs contains the unsafe binding.

zstd-safe provides minimum safe wrapper over zstd-sys, while zstd provides abstraction built on zstd-safe: encoder, decoder and related convenient functions.

> The version number "zstd v0.12.3+zstd.1.5.2" suggests that zstd 1.5.2 is used. Also, would it not make sense to update the version of zstd-safe in Cargo.toml of zstd-rs to v6.0.5+zstd.1.5.4?

The latest zstd-sys is 2.0.8+zstd.1.5.5, which cargo treated as 2.0.8

zstd depends on zstd-safe >=6.0.3, which depends on zstd-sys >=6.0.3
They are compatible based on cargo's semver rule, so you can simply update your lockfile to latest version.

If lockfile does not exist, then cargo by default would use the latest version.

**Comment by gyscos** [comment]
Yes I used the zstd lib version as metadata for all the crates initially, when I thought I'd pin the whole chain (zstd-safe would pin zstd-sys, and zstd would pin zstd-safe). Turns out that was a bad idea and only zstd-sys should embed the metadata in the version.

Just made a release to strip these metadata, should remove some of the confusion.
