### ISSUE TITLE
Update to Zstd 1.5.5 to avoid corruption in high compression scenarios

### ISSUE THREAD

**Issue by z3cko** [gyscos/zstd-rs#230]
Zstd 1.5.5 has been released already on 2023-04-05 to address a "[rare corruption bug that can occur in high compression modes](https://www.phoronix.com/news/Zstd-1.5.5)" but the [version of zstd-safe on crates.io still is v6.0.5+zstd.1.5.4](https://crates.io/crates/zstd-safe). Can I please ask you to release an update to match the version number of Zstd? In this particular case (where version 1.5.5 is a bugfix release to a corruption bug introduced in 1.5.4). It would be generally great if the version number of zstd-safe would always match the latest Zstd version.

**Comment by NobodyXu** [comment]
[zstd-sys v2.0.8+zstd1.5.5](https://docs.rs/zstd-sys/2.0.8+zstd.1.5.5/zstd_sys/) has been released for quite some time.

You just need to update your lockfile.

**Comment by NobodyXu** [comment]
P.S. This is a duplicate of #228

**Comment by z3cko** [comment]
Thanks for the clarification!
