### ISSUE TITLE
zstd_safe::decompress: it is not documented, that you need to have enough capacity

### ISSUE THREAD

**Issue by safinaskar** [gyscos/zstd-rs#236]
I tried to pass a vector as a first argument to `zstd_safe::decompress`. And it turned out I should have enough capacity to store all decompressed data. Please, document this

**Comment by gyscos** [comment]
Indeed, as documented it's a very thin wrapper around `ZSTD_decompress`, and all the same caveats and requirements apply. I added a paragraph to describe this particular point.
