### ISSUE TITLE
`zstd::Decoder`: provide configuration options

### ISSUE THREAD

**Issue by rMazeiks** [gyscos/zstd-rs#246]
I am trying to decode a ZST stream using a `zstd::Decoder`. Currently, it fails with the following error:

```
Error: Frame requires too much memory for decoding
```

After some research, I found that I need to increase the window size. I can do that for a `DCtx` context. In fact, if I set the `WindowLogMax=31` parameter in the `zstd-rs` source code as follows, the ZST is decoded correctly.

```
    pub fn with_dictionary(dictionary: &[u8]) -> io::Result<Self> {
        let mut context = zstd_safe::DCtx::create();

// +++
        context.set_parameter(DParameter::WindowLogMax(31)).unwrap();
// +++

        context.init().map_err(map_error_code)?;
        context
            .load_dictionary(dictionary)
            .map_err(map_error_code)?;
        Ok(Decoder { context })
    }
```

Of course, it doesn't make sense to hard-code this parameter here, as everyone's use case is different. But it would be nice if the Decoder API provided a way to configure these parameters. Perhaps a `with_dictionary_and_config` constructor that would also accept a `Vec<DParameter>` or something?

Thanks!

**Comment by gyscos** [comment]
Hi, and thanks for the report!

You might be interested in https://docs.rs/zstd/latest/zstd/stream/read/struct.Decoder.html#method.window_log_max, or https://docs.rs/zstd/latest/zstd/stream/read/struct.Decoder.html#method.set_parameter ?

**Comment by rMazeiks** [comment]
Yeah that works :smile: Thanks for the quick reply and sorry about that! For some reason I assumed this would only be set at construction time :/
