### ISSUE TITLE
WriteBuf documentation is unclear with regards to whether it will reallocate

### ISSUE THREAD

**Issue by Ten0** [gyscos/zstd-rs#259]
The [`WriteBuf`](https://docs.rs/zstd/latest/zstd/stream/raw/trait.WriteBuf.html) documentation says:
- "Describe a resizeable bytes container like Vec<u8>."
- "they will be resized to cover the data written"

This seems to suggest that it would reallocate the buffer as necessary, which ended up causing a bug here:
https://github.com/Ten0/serde_avro_fast/pull/11

It might be useful to clarify the documentation to precise that it will not ever reallocate, and that by "growable" and "resizing" we really mean "flagging uninitialized data as initialized by using `Vec::set_len`, but not actually grow the Vec's allocation".

Thanks,

**Comment by gyscos** [comment]
Thanks for the report!

Indeed, I understand the documentation is a bit confusing.

I tried to reword it in the latest commit, hope it helps avoid this kind of issues.

**Comment by Ten0** [comment]
Seems clear 👍
