### ISSUE TITLE
Add async integration

### ISSUE THREAD

**Issue by gyscos** [gyscos/zstd-rs#26]
Work started in the [async](https://github.com/gyscos/zstd-rs/tree/async) branch.

TODO:

- [x] Add `AsyncWrite` to `stream::Encoder`
  - [x] Add tests
- [x] Add `AsyncRead` to `stream::Decoder`
  - [x] Add tests

**Comment by sid0** [comment]
@gyscos would you like to do this yourself? If not I have someone else at Facebook interested in tackling this.

**Comment by gyscos** [comment]
I would definitely appreciate help, especially for the tests.
I wrote the `AsyncWrite` implementation looking at how it was done in flate2, but I don't really know how to use it yet - I haven't had time to look at actual tokio code yet.

**Comment by vladima** [comment]
I guess this issue now can be closed.
