### ISSUE TITLE
The lack of fast methods in the high-level wrapper

### ISSUE THREAD

**Issue by ArtemGr** [gyscos/zstd-rs#27]
The high-level Rust wrapper is not zero-cost. It uses some nice abstractions but with a huge performance hit. Even though the hit might be reduced, I think the high-level wrapper needs a way to safely use Zstandard in a zero-cost way!

Here's what I got on my Opteron:

decode_all .. 20,434 ns/iter
ZSTD_decompress .. 428 ns/iter
ZSTD_decompressDCtx .. 74 ns/iter

Benchmark:

```
#[bench] fn zstd_high (bencher: &mut Bencher) {
  use zstd::stream::{encode_all, decode_all};
  let text = "Eeny, meeny, miny, moe";
  let compressed = encode_all ("Eeny, meeny, miny, moe".as_bytes(), 3) .unwrap();

  bencher.bytes = text.len() as u64;
  bencher.iter (|| {
    assert_eq! (decode_all (&compressed[..]) .unwrap(), text.as_bytes())});}

#[bench] fn zstd_direct (bencher: &mut Bencher) {
  use zstd::stream::encode_all;
  use zstd_sys;
  let text = "Eeny, meeny, miny, moe";
  let compressed = encode_all ("Eeny, meeny, miny, moe".as_bytes(), 3) .unwrap();

  let zctx = unsafe {zstd_sys::ZSTD_createDCtx()};

  bencher.bytes = text.len() as u64;
  bencher.iter (|| {
    const BUF_SIZE: usize = 2048;
    let mut buf: [u8; BUF_SIZE] = unsafe {uninitialized()};
    let rc = unsafe {zstd_sys::ZSTD_decompressDCtx (zctx, buf.as_mut_ptr() as *mut c_void, BUF_SIZE, compressed.as_ptr() as *const c_void, compressed.len())};
    assert_eq! (0, unsafe {zstd_sys::ZSTD_isError (rc)});
    assert_eq! (&buf[..rc], text.as_bytes())
  });

  unsafe {zstd_sys::ZSTD_freeDCtx (zctx);}}
```

```
running 2 tests
test by_test::zstd_direct                   ... bench:          74 ns/iter (+/- 14) = 297 MB/s
test by_test::zstd_high                     ... bench:      20,434 ns/iter (+/- 17,473) = 1 MB/s
```

Second run:
```
running 2 tests
test by_test::zstd_direct                   ... bench:          64 ns/iter (+/- 3) = 343 MB/s
test by_test::zstd_high                     ... bench:      10,521 ns/iter (+/- 931) = 2 MB/s
```

**Comment by gyscos** [comment]
Indeed, `decode_all` creates a new context for each call. This is usually fine for large transfers, but suffers with little buffers - there's definitely something we can do here.
That being said, I'll look into adding a low-level module as a thin, safe layer above the direct FFI.

**Comment by ArtemGr** [comment]
> That being said, I'll look into adding a low-level module as a thin, safe layer above the direct FFI.

Great!

I'm particularly interested in the `ZSTD_compressBlock` functions, since they'd let me avoid the frame header overhead. So if you want something tested, drop me a note.

**Comment by gyscos** [comment]
I also just realized you were comparing `decode_all`, which uses the stream format, and `ZSTD_decompressDCtx`, which decompresses a single block.
`block::Decompressor` may be what you're looking for: it uses the block format, and re-uses the context between multiple calls.

**Comment by ArtemGr** [comment]
> I also just realized you were comparing decode_all, which uses the stream format, and ZSTD_decompressDCtx, which decompresses a single block.

Nah, ZSTD_decompressDCtx would decompress all the frames of a stream AFAIK.

**Comment by gyscos** [comment]
Its `decompress` method writes to a buffer, but `Decompressor::decompress_to_buffer` is also public, and is pretty much the low-level abstraction you're after.

**Comment by ArtemGr** [comment]
That. But the method I'm after is `ZSTD_decompressBlock` and I might be mistaken, but `zstd::block::Decompressor` using `ZSTD_decompress_usingDict` looks fishy to me. It's like using TCP on the IP or MAC level.

You should be able to use the `ZSTD_decompressBlock` with a dictionary too, cf. https://github.com/facebook/zstd/issues/664

**Comment by gyscos** [comment]
`ZSTD_decompressDCtx` is really just a shortcut for `ZSTD_decompress_usingDict` with an empty dictionary, so it would be a good fit for the benchmark above.

As for even lower-level methods like `ZSTD_decompressBlock`, I'll see what I can do.

**Comment by ArtemGr** [comment]
> ZSTD_decompressDCtx is really just a shortcut for ZSTD_decompress_usingDict with an empty dictionary, so it would be a good fit for the benchmark above.

It would, thanks!
But please note that instead of keeping the dictionary in `Decompressor::dict` you ought to get better results passing by it to `ZSTD_createDDict` and using `ZSTD_decompress_usingDDict`.

**Comment by gyscos** [comment]
I just published an intermediate library, `zstd-safe`: it is an almost 1-for-1 mapping from `zstd-sys` to a safe, rustic-ish API (with slices instead of pointers + length). It can be a nicer option than `zstd-sys` itself if you need more control than the higher-level library provides.

**Comment by ArtemGr** [comment]
Works fine, thanks.

(I'm still using zstd_sys, because I'm aiming for the Block level API compression, but zstd-safe is a step forward to having a faster general-purpose zstd compression).
