### ISSUE TITLE
How make a `ZstdFile` like object?

### ISSUE THREAD

**Issue by mamcx** [gyscos/zstd-rs#311]
I wish to transparently replace my file io with compressed data, and `zstd` look like is the best overall compression lib for this (need fast decompression).

But have a hard time figuring out how build a `ZstdFile` object, that not rebuild in `write/read` the `Encoder/Decoder`. 

I need to create a interface like:

```rust
pub struct ZstdRW<RW:Read+Write> {
    inner: RW,
}
```

**Comment by gyscos** [comment]
Hi, and thanks for the question!

At the moment there is no `ZstdFile` equivalent, that would provide both `Write` and `Read` on the same object. Instead, it is recommended to focus on one side at a time.

Do you really need something that implements `Read + Write`? If so, it may be easier to embed both a `Decoder` and an `Encoder`, and redirect each implementation of `Read`/`Write` to the proper one.

**Comment by mamcx** [comment]
>  If so, it may be easier to embed both a Decoder and an Encoder

I tried that but both cause issues with the borrow checker:


```rust
pub struct ZstdRW2<'a, RW: Read + Write> {
    encoder: Encoder<'a, &'a mut RW>,
    decoder: Decoder<'a, BufReader<&'a mut RW>>,
}

impl<'a, RW: Read + Write> ZstdRW2<'a, RW> {
    pub fn new(inner: &'a mut RW) -> Self {
        let encoder = Encoder::new(inner, 10).unwrap();
        let decoder = Decoder::new(inner).unwrap();
        Self { encoder, decoder }
    }
}
```

```rust
173 |     pub fn new(inner: &'a mut RW) -> Self {
    |                ----- move occurs because `inner` has type `&mut RW`, which does not implement the `Copy` trait
174 |         let encoder = Encoder::new(inner, 10).unwrap();
    |                                    ----- value moved here
175 |         let decoder = Decoder::new(inner).unwrap();
    |                                    ^^^^^ value used here after move
```

**Comment by mamcx** [comment]
With minor fixes it worked.
