### ISSUE TITLE
Name the default level?

### ISSUE THREAD

**Issue by dpc** [gyscos/zstd-rs#33]
I wish there was a constant for the default level to use. Related: https://github.com/facebook/zstd/issues/89

**Comment by gyscos** [comment]
I don't think there is a clear default level for now.

The `zstd` cli tool has an internal default level (set to 3) set in `programs/zstdcli.c`, and is not publicly exposed.
The API itself has its own internal default level, again set to 3 and not exposed, used when the given level is 0 (and also for the new, experimental advanced API).

I could add a `0` constant to use as default level, but I think it's easier (and less confusing to people reading this constant) to simply document the compression functions about this "0 as default" behaviour.

**Comment by dpc** [comment]
I'm glad I've asked. I've used 5. :)

**Comment by ajkr** [comment]
Is it documented or exposed as a constant now? Either one would be useful, as long as we can rely on the meaning of zero not changing in the future.

**Comment by gyscos** [comment]
On master we now define `zstd::DEFAULT_COMPRESSION_LEVEL` (as a re-export from the CLEVEL_DEFAULT). Currently, it is 3.

**Comment by gyscos** [comment]
`zstd::compression_level_range()` now provides access to the max and min levels.
