### ISSUE TITLE
Block `Compressor` and `Decompressor` should be able to take the dictionary as a static reference

### ISSUE THREAD

**Issue by rocallahan** [gyscos/zstd-rs#42]
Currently you have to pass the dictionary in as a `Vec<u8>`. I see no reason to require dynamic allocation here; you could use a `Cow<[u8]>` and allow passing owned or referenced data.

**Comment by gyscos** [comment]
Compressor and Decompressor have been refactored a bit in the meantime and now accept a `&[u8]` dictionary, like `Encoder` and `Decoder`.

I will close this issue for now, feel free to re-open as necessary.
