### ISSUE TITLE
Implement BufRead trait for Decoder

### ISSUE THREAD

**Issue by drrlvn** [gyscos/zstd-rs#43]
Since `Decoder` already has a buffer then implementing `BufRead` using that buffer should be inexpensive and allow using the useful methods this trait provides.

Wrapping a `Decoder` in a `BufReader` adds another buffer which is redundant.

**Comment by gyscos** [comment]
That's a great idea!

**Comment by gyscos** [comment]
Actually, the buffer used by `Decoder` is used for its input - it's where the inner `Read` stores its output, _before_ being fed to `zstd`.
After decompression, `Decoder` doesn't currently buffer anything. So in this case, there is no advantage to implement `BufRead` by adding a buffer, and just wrapping it in a `BufReader`.
