### ISSUE TITLE
confused by performance gap relative to zstd-safe

### ISSUE THREAD

**Issue by jonathanstrong** [gyscos/zstd-rs#54]
I'm encountering roughly 10x worse performance (speed) with `zstd::block::Compressor::compress_to_buffer` relative to `zstd_safe::compress_using_cdict` or `zstd_safe::compress_cctx`, and 4-5x worse decompression performance (speed):

```console
test sender::tests::zstd_block_compressor_nodict_compress_to_buffer_3049_byte_json        ... bench:      14,652 ns/iter (+/- 204)
test sender::tests::zstd_block_compressor_with_dict_compress_to_buffer_3049_byte_json     ... bench:     119,456 ns/iter (+/- 730)
test sender::tests::zstd_block_decompressor_with_dict_decompress_to_buffer_3049_byte_json ... bench:      21,099 ns/iter (+/- 493)
test sender::tests::zstd_safe_compress_cctx_3049_byte_json                                ... bench:      14,732 ns/iter (+/- 85)
test sender::tests::zstd_safe_compress_using_cdict_3049_byte_json                         ... bench:       9,998 ns/iter (+/- 73)
test sender::tests::zstd_safe_decompress_dctx_3049_byte_json                              ... bench:       5,969 ns/iter (+/- 37)
test sender::tests::zstd_safe_decompress_using_ddict_3049_byte_json                       ... bench:       4,188 ns/iter (+/- 42)
test sender::tests::zstd_stream_encoder_with_dictionary_3049_byte_json                    ... bench:     306,225 ns/iter (+/- 1,511)
```

I noticed that `zstd::block::Compressor` is using `zstd_safe::compress_with_dict`, which accepts a byte slice of the dictionary instead of `zstd_safe::compress_with_cdict`, which accepts a "prepared" dictionary - perhaps that could be the issue? It's likely only significant for small data, but zstd is one of the best options for small data with the dictionary functionality, so it seems preferable to "prepare" the dictionary once, up front instead of every compression.

**Comment by JakubOnderka** [comment]
Yes, that could be the problem, because the documentation for `zstd_safe::compress_using_dict` function explain this: *This function loads the dictionary, resulting in significant startup delay.* So if you want to reuse dictionary, it is better to use `zstd_safe::compress_using_cdict` or create dictionary by [zstd::dict::EncoderDictionary](https://docs.rs/zstd/0.4.21+zstd.1.3.7/zstd/dict/struct.EncoderDictionary.html) and then use [zstd::stream::Encoder::with_prepared_dictionary](https://docs.rs/zstd/0.4.21+zstd.1.3.7/zstd/stream/struct.Encoder.html#method.with_prepared_dictionary).

**Comment by jonathanstrong** [comment]
Don't you think it would make more sense for the `zstd::block::Compressor` api to store prepared dictionary internally and use it for `compress_to_buffer`? The overhead of preparing the dictionary will happen at some point anyway. You could store an `Option<_>` for the cdict for when a dictionary is not in use, and match on it to decide which `zstd_safe` function to use. I'm happy to submit a pr with your ok.

**Comment by JakubOnderka** [comment]
I think `zstd::block::Compressor` and `zstd::block:Decompressor`  should implement the same API as stream Decoder and Encoder and provide `with_prepared_dictionary` method.

**Comment by gyscos** [comment]
I agree ; I mostly focused on the encoder until now and didn't update the compressor when I added prepared dicts.

**Comment by jonathanstrong** [comment]
Ok. Do you think the underlying implementation should behave differently (i.e. store a `&[u8]` or `Vec<u8>` when `with_dictionary` is called, and store an `&EncoderDictionary` if `with_prepared_dictionary` is called? It seems like there's no good reason to store the bytes (either as `&[u8]` or `Vec<u8>` in a `Compressor` regardless of which method (`with_dictionary` or `with_prepared_dictionary`) is called, since even in the case of `with_dictionary` an `EncoderDictionary` (the zstd equivalent) will still be constructed.

**Comment by gyscos** [comment]
Yeah, using the encoded one in all cases probably makes sense.
As for where the bytes belong, I still need to think a bit about this. May end up with a `Cow` or something similar.

**Comment by jonathanstrong** [comment]
According to the zstd docs, the underlying bytes used to construct the dictionary object can be moved/deleted/etc after construction - the `CDict` just uses them once on construction:

```
ZSTD_CDict* ZSTD_createCDict(const void* dictBuffer, size_t dictSize,
                             int compressionLevel);

  When compressing multiple messages / blocks with the same dictionary, it's recommended to load it just once.
  ZSTD_createCDict() will create a digested dictionary, ready to start future compression operations without startup delay.
  ZSTD_CDict can be created once and shared by multiple threads concurrently, since its usage is read-only.
  `dictBuffer` can be released after ZSTD_CDict creation, since its content is copied within CDict
  Note : A ZSTD_CDict can be created with an empty dictionary, but it is inefficient for small data. 

```

However, there's a bit of a problem with matching the api of `Encoder` because `Encoder::with_prepared_dictionary` takes a `&EncoderDictionary` (using it once to start the stream context), whereas `Compressor` would store its dictionary, forcing it to track the lifetime of the underlying `EncoderDictionary` in everything it does. It would be much simpler for `Compressor` to simply own it's own `EncoderDictionary`, perhaps it could clone a `&EncoderDictionary`? It would be a somewhat misleading api, but it would match.

**Comment by gyscos** [comment]
Ah nice, I must have misremembered that.
Regarding the API, I think it's fine to have `Compressor` use a different API and directly take a `EncoderDictionary`, letting users clone it if needed.
Right now, `EncoderDictionary` doesn't implement `Clone`, but I could update it to use `Arc` internally (since CDict is `Send`+`Sync`).

**Comment by gyscos** [comment]
Actually the current `Encoder::with_prepared_dictionary` seems completely broken: `ZSTD_initCStream_usingCDict` expects the dictionary to outlive the context, which we don't enforce at all. Doh.

**Comment by JakubOnderka** [comment]
> Actually the current `Encoder::with_prepared_dictionary` seems completely broken: `ZSTD_initCStream_usingCDict` expects the dictionary to outlive the context, which we don't enforce at all. Doh.

When it can be problem? Because I think Rust will not release dictionary memory before releasing whole Encoder. Or can you provide an example when this situation can happened?

**Comment by gyscos** [comment]
```rust
fn create_encoder<W: Write>(w: W) -> io::Result<Encoder<W>> {
    let data = vec![1,2,3,4,5,6,7,8,9,0];
    let dict = EncoderDictionary::new(&data, 1);
    Encoder::with_prepared_dictionary(w, &dict)
}
```

`zstd_safe::init_cstream_using_cdict` mandates that the dict outlives the context. This means the context should have a lifetime, and the lifetime of the dict should outlive it.

**Comment by gyscos** [comment]
Ah, another small issue: when using a pre-digested dictionary, we need to specify the compression level up-front. Currently, it is given in `Compressor::compress_to_buffer`.
Solutions might be:
* Always specify the level when creating the `Compressor`, and disallow using the same compressor with multiple levels.
* Cache one or more digested dictionaries, and re-digest it if a different compression level is used.

The problem with the first solution is that it also affects users who don't need dictionaries.

**Comment by gyscos** [comment]
> Ah, another small issue: when using a pre-digested dictionary, we need to specify the compression level up-front. Currently, it is given in `Compressor::compress_to_buffer`. Solutions might be:

The previously-named "block" module has now be renamed to "bulk" and refactored; it now uses a zstd context internally, and doesn't have that issue anymore.

I'll close this ticket as I think the core issue has been solved; feel free to re-open if you think it's not the case.
