### ISSUE TITLE
Fix broken `Encoder::with_prepared_dictionary`

### ISSUE THREAD

**Issue by gyscos** [gyscos/zstd-rs#55]
Follow-up from #54 

The current method imposes no lifetime constraints; but zstd specifies that the dictionary must outlive the context in this situation (since the context merely references the dictionary without copying it).

We will need to:
* Update `zstd-safe` to add a lifetime to `CStream`.
* In the `zstd` crate, update the `Encoder` to include something like an `Option<Arc<EncoderDictionary>>` (so it can be shared) and have the context borrow from it. This means `Encoder` will be a kind of self-referential struct, and we'll likely need something like `owning_ref`: a `OwningHandle<Option<Arc<EncoderDictionary>>, zstd_safe::CStream>`.

**Comment by gyscos** [comment]
Note that `zstd_safe::CDict` itself needs a lifetime, as it may be only reference the dictionary data.
For the zstd crate, the easy solution is probably to always use `CDict<'static>` and never reference data, at least for now. This lets us avoid adding a lifetime to `EncoderDictionary`.
Otherwise, an alternative could be to embed a `Arc<[u8]>` in `EncoderDictionary` along with the `CDict`, using `owning_ref::OwningHandle` much like the solution described above for `Encoder`.

**Comment by phiresky** [comment]
I think I just encountered this issue because I was getting segfaults.. took me a while to find  the cause. Would be great if this could be fixed or at least the API marked unsafe. In the code I'm using, I'm using this:

```rust
pub fn wrap_encoder_dict(dict_raw: Vec<u8>, level: i32) -> OwnedEncoderDict<'static> {
    owning_ref::OwningHandle::new_with_fn(dict_raw, |d| {
        Box::new(EncoderDictionary::new(
            unsafe { d.as_ref() }.unwrap(),
            level,
        ))
    })
}

let dict = Arc::new(wrap_encoder_dict(vec, 10));

encoder = zstd::stream::write::Encoder::with_prepared_dictionary(out, &dict);

encoder.write(...)
```

It segfaults in the write function because of a free call when the block containing the with_prepared_dictionary ends.

**Comment by gyscos** [comment]
Indeed! I finally rewrote some of the lifetime bounds here and it should be more reasonable.
