### ISSUE TITLE
Fix block compressor API with dictionaries

### ISSUE THREAD

**Issue by gyscos** [gyscos/zstd-rs#56]
Follow-up from #54 

The current API for block compression using dictionaries is not ideal:
* Impossible to share a dictionary (`Compressor` stores a `Vec<u8>`)
* Impossible to use a prepared dictionary for higher performance (dictionary is re-hashed every time)

We want to:
* Use shared ownership of the dictionary as much as possible
* Keep a map of prepared dictionaries. When compressing a new block, use the prepared dictionary for the given compression level, or prepare a new one if needed. We'll keep the raw dictionary around in case we need to prepare more dictionaries, but the `CDict` itself copies the data internally and doesn't reference the raw data - this means no lifetime mess and no need for `owning_ref` here.
* When not using a dictionary, don't prepare a digested dictionary and directly use `compressCCtx` - using an empty prepared dictionary is possible, but less efficient.

**Comment by gyscos** [comment]
Well, turns out I was severely mistaken and this API should actually be called bulk rather than block. The true zstd block API builds a succession of compressed blocks, each depending on the previous ones. This is not what the current `block` module does.

So in addition to the above work, we will need to rename block to bulk, and maybe implement an actual block API.

**Comment by brianc118** [comment]
@gyscos Thanks for your work on this library!

> Impossible to share a dictionary (`Compressor` stores a `Vec<u8>`)

Any plans for this to happen soon? Would this be a big change? This problem has caused us to use the streaming interface (`with_prepared_dictionary`) instead of the block interface, which I believe makes it less efficient.

**Comment by terrelln** [comment]
> and maybe implement an actual block API.

That probably isn't necessary. (Almost) no one uses zstd's block API, and we're considering removing it in the future, or making it much harder to access.

> So in addition to the above work, we will need to rename block to bulk

I think a rename might help clarity. `bulk` or `simple` would make sense to me.

You should be able to wrap zstd's advanced [compression](https://github.com/facebook/zstd/blob/f4a552a3fa24d9078f84157bd40e4f1bad49c488/lib/zstd.h#L240-L525) and [decompression](https://github.com/facebook/zstd/blob/f4a552a3fa24d9078f84157bd40e4f1bad49c488/lib/zstd.h#L528-L589) APIs. They are compatible with both streaming and the simple `ZSTD_compress2()` and `ZSTD_decompress()` functions. You can set any parameter, and use any kind of dictionary using this API.

**Comment by gyscos** [comment]
Latest commit should rename the module to `bulk`, and rework it to be closer to the streaming API in term of dictionary handling and parameters.

It also gives direct access to the underlying context if needed.

**Comment by terrelln** [comment]
Awesome! Thanks for the amazing work maintaining `zstd-rs` @gyscos!
