### ISSUE TITLE
"Error (generic)" when training dict using any method

### ISSUE THREAD

**Issue by davechallis** [gyscos/zstd-rs#57]
On Mac OS X, rustc 1.31.1, using `zstd 0.4.21+zstd.1.3.7` and `zstd-safe 1.4.6+zstd.1.3.7`, I get a generic error when trying to create a dict from samples, e.g.:

    use zstd;

    fn main() {
        let _dict = zstd::dict::from_samples(&["foo"], 10000).unwrap();
    }

results in:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("Error (generic)") }', libcore/result.rs:1009:5

The same happens with `from_files` with a similar example.

Edit: same error with `zstd v0.4.22+zstd.1.3.8` and `zstd-sys v1.4.7+zstd.1.3.8`.

**Comment by gyscos** [comment]
Hmm I think it's caused by too few samples; the dictionary builder is a bit tricky and has some requirements.
We probably could improve the returned error.

**Comment by davechallis** [comment]
@gyscos thanks, that indeed seems to be the case - increasing the number of samples to a few thousand gets everything working correctly.
