### ISSUE TITLE
Duplicate symbols error

### ISSUE THREAD

**Issue by terrelln** [gyscos/zstd-rs#58]
I'm not a rust expert, so forgive my terminology. This crate should hide all libzstd symbols in the `rlib`. Otherwise, when using the `zstd-sys` module, and linking with other C/C++ code that also uses zstd, you will get duplicate symbol warnings.
    
You can get zstd to hide all of its symbols with these compiler flags:

```
-DZSTDLIB_VISIBILITY=
-DZDICTLIB_VISIBILITY=
-DZSTDERRORLIB_VISIBILITY=
-fvisibility=hidden
```

See the example in [python-zstandard](https://github.com/indygreg/python-zstandard/blob/master/setup_zstd.py#L157).

**Comment by gyscos** [comment]
Good point! I'll add these flags.

**Comment by gyscos** [comment]
I published `zstd-sys` 1.4.8, which should add these options.
Does it solve the problem?
Even better, do you have a test case for this we could add/document somewhere?

**Comment by terrelln** [comment]
You can `nm -g zstd-sys.rlib | grep -e ZSTD -e ZDICT -e HUF -e FSE` (or whatever the rlib is called). If there are no symbols listed as `T` then the patch likely worked. 

Sorry, I spent some more time on this, but forgot to update this issue. The visibility setting (`-fvisibility=hidden`) sadly doesn't work because afaik the `rlib` is a static object, not a shared library.

I'm not sure how to fix this issue. I'm looking for help from Rust users internally. If we find a fix, I'll update you here.

**Comment by gyscos** [comment]
Than you for the analysis!

When you say `zstd-rs` uses the unstable API, which part are you talking about? Do you mean the experimental bits in `zstd-sys` and `zstd-safe`? The top-level `zstd` crate itself ideally shouldn't be using these.

From what I understand, we can link zstd either statically or dynamically; and we can either use the local submodule, or an externally-provided one (maybe the system version). This results in 4 possible situations, though the most common are probably statically-linked locally-built version, and dynamically-linked system-provided version. Dynamically-linking the locally-built library doesn't sound very interesting, but I suppose statically-linked provided-version might be desirable (as you mention, when using pkgconfig)?

I understand that dynamic linking precludes us from using/exposing unstable part of zstd (like some of the experimental parameters). When statically linking a provided version of zstd, I'm not so sure - we might need to re-run bindgen with the provided header, but I think allowing unstable features would be safe in this case.

**Comment by terrelln** [comment]
Any functions that require `ZSTD_STATIC_LINKING_ONLY` are part of the unstable API. Note that in the next zstd version we are stabilizing the new advanced API, which should be everything `zstd-rs` needs. If its not, please let us know before we make the next release!

We're interested in statically linking a provided-version of zstd. We want `zstd-rs` to have a feature flag to use the stable API, so that we can always link in a newer version of zstd than `zstd-rs` expects.

For example, we couldn't use zstd-1.3.8 with zstd-rs build with zstd-1.3.7, since we renamed a bunch of unstable functions / parameters (`ZSTD_p_compressionLevel` -> `ZSTD_c_compressionLevel`), so `zstd-safe` would break. Even if we statically link zstd in, if its not the version `zstd-safe` expects, things could break.

Once symbols are in the stable API, they will never change, so if `zstd-rs` only uses the stable API it will only impose a lower bound on the zstd version used, not an exact match.

**Comment by gyscos** [comment]
Wow, I had a look and indeed, `zstd-rs` is using a bunch of experimental functions.

So the first step will be to add an `experimental` feature flag to `zstd-sys` and `zstd-safe` that triggers `ZSTD_STATIC_LINKING_ONLY`. `zstd-rs` will, for now, use this `experimental` flag.

Next, we'll need to add a way for `zstd-sys` to link statically to another version of `zstd`. For that, we'll need to know the location of the header (to re-run bindgen), and the location of the lib (to add to the lib path). I'm not 100% sure how to do that yet - probably through environment variables, combined with another feature flag. `pkg-config` might be an option (will check https://github.com/alexcrichton/pkg-config-rs).

**Comment by jsgf** [comment]
Yeah, I talked with @terrelln about using pkgconfig - I think it would work out.

The other problem we're having is that when setting the `bindgen` feature for `zstd-sys`, it runs into issue https://github.com/rust-lang/cargo/issues/5237, since we have other crates which are also using bindgen. Unfortunately I don't think there's a satisfactory fix or workaround, except if we locally modify some or all of those crates to use the same version of `bindgen`.

**Comment by gyscos** [comment]
On master there is now an `experimental` feature flag for `zstd-sys` and for `zstd-safe`, which is used to expose the unstable API. `zstd-rs` itself still uses this flag for now.

I also updated `zstd-sys` with more pre-computed bindings (with/without experimental support, using std or libc types), so `bindgen` should be required less often (though it might still be necessary when used with pkg-config).

**Comment by terrelln** [comment]
Hi @gyscos, I'm preparing to release zstd-1.4.0 in the next week or two. The new advanced API is now part of the stable API in the development branch, and won't change between now and the release.

I believe that all the functionality you need in `zstd-rs` is now available in the stable API, except for maybe very minor use cases, which could be hidden behind an `experimental` feature. It would be great to see `zstd-rs` migrate to only using the stable API!

In the meantime, if you find that you are missing some critical functionality in the stable API, please let me know!

**Comment by terrelln** [comment]
zstd-1.4.0 has been released.

Hopefully everything you need is in the stable API, which will make updating zstd versions much easier, since the stable API will never change. If you find you are missing something important, please let us know.
