### ISSUE TITLE
crate includes semver metadata that will be ignored by cargo 

### ISSUE THREAD

**Issue by untitaker** [gyscos/zstd-rs#62]
While building, cargo outputs this:

```warning: version requirement `0.4.24+zstd.1.4.0` for dependency `zstd` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion```

Not really a problem with this crate, but why include this metadata in the first place? Related: https://github.com/killercup/cargo-edit/issues/303

**Comment by gyscos** [comment]
It's used to help users know what version of the C lib is being used. It's purely informative and as you mention has no impact on any version check from cargo. It can (and should probably) be omitted when specifying the dependency version.

**Comment by mitsuhiko** [comment]
For what it's worth I just realized that this also makes crates.io lie about the latest version. The actual latest version is 0.4.24 but crates.io thinks it's 0.4.14.

**Comment by gyscos** [comment]
Yeah, the bug on crates.io has been open for some time and has received little love so far. Other frontends like docs.rs and lib.rs do work fine. I think there's just not many people actively working on the crates.io website these days.
