### ISSUE TITLE
zstd v1.4.1

### ISSUE THREAD

**Issue by JakubOnderka** [gyscos/zstd-rs#63]
Hi,

zstd v1.4.1 was [released](https://github.com/facebook/zstd/releases/tag/v1.4.1) and it would be nice to update also zstd-rs, because it provides some performance improvements and few bug fixes.

**Comment by gyscos** [comment]
Thanks!
Published `zstd-0.4.26` which links to zstd v1.4.1. I also updated `zstd-safe` to depend on an exact version of `zstd-sys`, and `zstd` to depend on an exact version of `zstd-safe`.

**Comment by JakubOnderka** [comment]
Great, thanks!
