### ISSUE TITLE
Parallel (de)compression

### ISSUE THREAD

**Issue by thedrow** [gyscos/zstd-rs#64]
Most bindings I know support parallel (de)compression of Zstd blocks.
It'd be nice to have that API in these bindings as well.

**Comment by gyscos** [comment]
Agreed! I think moving to the advanced API will help enable that.

**Comment by gyscos** [comment]
I updated `zstd-safe` to better expose the advanced options, and use it in the top-level crate for 2 options so far: checksum, and parallel compression.
Note that I'll need to enable multi-threading when building `zstd` in `zstd-sys`...

**Comment by JJJollyjim** [comment]
Does that mean this should be working in the current version?

I have `features = ["zstdmt"]` on `zstd-safe` in my `Cargo.toml`, but I can't get past "Unsupported parameter" when calling `encoder.multithread`.

**Comment by andoriyu** [comment]
@JJJollyjim have you ever solve this?

**Comment by andoriyu** [comment]
@gyscos I've figured it out. PR incoming.
