### ISSUE TITLE
Add support for checksum?

### ISSUE THREAD

**Issue by yongqli** [gyscos/zstd-rs#66]
Currently the produced zstd data does not include a checksum (as examined by `zstd -l`). Are there any plans for adding a way to configure the Encoder with additional options?

**Comment by gyscos** [comment]
Hi! Thanks for the report.

Indeed we're not currently enabling checksum during compression, but it is planned!
In general I need to update this crate to the new "advanced" API, which should make it easier to toggle individual options.

**Comment by gyscos** [comment]
On latest master, encoders should now have a `include_checksum()` method to enable that.

**Comment by yongqli** [comment]
Ok, thanks!
