### ISSUE TITLE
Encoder::finish prevents use in struct

### ISSUE THREAD

**Issue by bruceg** [gyscos/zstd-rs#7]
I am using an Encoder within a struct, to which I only have a mut reference. According to the docs, I need to call Encoder::finish before dropping the stream, but finish consumes self. Since Rust cannot move out of a borrowed reference, it cannot call finish().

Creating an AutoFinishEncoder is also unsatisfactory, because errors from the finish method can no longer be handled.

The finish method should take only a reference to self, and return Result<()> similar to flush().

This is, of course, assuming finish() does something more than just calling flush() at the end, which is my reading of the documentation: "You need to call this after writing your stuff."

**Comment by gyscos** [comment]
`finish()` closes the stream, so nothing should be written after that (at least through the `Encoder`).
This means the `Encoder` becomes unusable after that, which is rather in line with taking `self` by value.
If you want your struct to keep living after calling finish, it means it'll be in a state where it can't write to the `Encoder`. A good model of that is to keep the `Encoder` in an `Option`, and call `take()` on it.

**Comment by gyscos** [comment]
Does the solution above apply? Or is this still an issue?

**Comment by bruceg** [comment]
I understand the reason for this design, and have seen at least one other compressor using it. I have since moved to a different design for my own project that avoids the issue I was having.
