### ISSUE TITLE
Builds do fail on Windows on Travis

### ISSUE THREAD

**Issue by rugk** [gyscos/zstd-rs#77]
Just in case you did not notice: Your CI build is failing

https://travis-ci.org/gyscos/zstd-rs
e.g. https://travis-ci.org/gyscos/zstd-rs/jobs/634379540

> error occurred: Command "gcc.exe" "-O3" "-ffunction-sections" "-fdata-sections" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-fvisibility=hidden" "-DZSTD_LIB_DEPRECATED=0" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-DZSTD_LEGACY_SUPPORT=1" "-o" "C:\\Users\\travis\\build\\gyscos\\zstd-rs\\target\\debug\\build\\zstd-sys-df2ee4e12446f4cc\\out\\zstd\\lib\\compress\\huf_compress.o" "-c" "zstd\\lib\\compress\\huf_compress.c" with args "gcc.exe" did not execute successfully (status code exit code: 1).

Maybe related to #69 or #76? (/cc @amrx101 and @expenses)

**Comment by gyscos** [comment]
Thanks! I'm still not quite sure what is causing this. I don't have a lot of experience with the gcc/msvc mix that happens with rust on windows - I'll try setting `DYNAMIC_BMI2=0` and see if that fixes it.

**Comment by gyscos** [comment]
I have now moved CI to github actions, and the current windows build seem to pass find:
https://github.com/gyscos/zstd-rs/actions/workflows/windows.yml

Will close this for now, feel free to re-open if you are still having issues!
