### ISSUE TITLE
support for async-std

### ISSUE THREAD

**Issue by zTrix** [gyscos/zstd-rs#79]
I've seen async operation is supported as an optional feature for tokio in the source code, any plan or example for async-std users?

**Comment by gyscos** [comment]
Thanks for the report!

Indeed, supporting async-std would be great. It seems to re-export the AsyncWrite trait from the futures crate, while tokio redefines its own (a shame, I hoped they could use the same trait).

**Comment by Nemo157** [comment]
If you don't want to support the boilerplate wrapper to map the async IO traits to the compression codecs, https://docs.rs/async-compression is doing that already for this and other formats.

**Comment by gyscos** [comment]
Leaving async support to async-compression for now is a great idea.
