### ISSUE TITLE
zstd::stream::write::Decoder doesn't flush on Drop

### ISSUE THREAD

**Issue by glandium** [gyscos/zstd-rs#80]
The equivalent in both flate2 (`flate2::write::ZlibDecoder`) and bzip2 (`bzip2::write::BzDecoder`) do flush on Drop.

**Comment by gyscos** [comment]
Hi, and thanks for the report!

That's a good point, we probably should align on the same behaviour.

**Comment by sharksforarms** [comment]
I got burnt by this :(

I end up calling `flush` before `into_inner`, would be nice if it was more consistent with other compression apis! Another one is `brotli::enc::DecompressorWriter`

**Comment by gyscos** [comment]
Latest commit should bring a `AutoFlushDecoder` to match the `AutoFinishEncoder`. It will flush on drop, and run a callback on the result (for example unwrapping).

**Comment by andrewbaxter** [comment]
I just got bit by this too. Is there a reason this isn't default behavior?

For the record, I'm using `Decoder` with `zio::Writer`, and it doesn't seem to be possible to use `AutoFlushDecoder` with it (or at least I'm not sure which combination of imports/parameters will allow it to compile).

**Comment by gyscos** [comment]
The issue is that any error that happens during flushing (for example, the underlying connection was closed) would result in panic, which is not the desired behavior in all cases (you'd often want to properly handle/report the error instead).
