### ISSUE TITLE
LICENSE of zstd-safe and zstd-sys

### ISSUE THREAD

**Issue by Fabian-Gruenbichler** [gyscos/zstd-rs#82]
the pre-generated bindings shipped in zstd-sys, as well as API-describing comments in zstd-safe are (partly) copied verbatim from libzstd's zstd.h, without attribution.

zstd.h contains the following:
```
/*
 * Copyright (c) 2016-present, Yann Collet, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under both the BSD-style license (found in the
 * LICENSE file in the root directory of this source tree) and the GPLv2 (found
 * in the COPYING file in the root directory of this source tree).
 * You may select, at your option, one of the above-listed licenses.
 */
```

which means you need to include proper attribution under the BSD-3-clause license in these two crates. for zstd-sys at least it probably makes sense to switch the whole crate over to BSD-3-clause, since it's almost entirely code directly generated from zstd.h.

**Comment by gyscos** [comment]
Blast! I missed that.

I started a branch to include the BSD license in the pre-generated binding files: https://github.com/gyscos/zstd-rs/pull/83

Would that work? I believe most distributions already include the `zstd` subfolder with its own `LICENSE` file.

As for comments in `zstd-safe`, I added a note saying that some of the documentation comes from `zstd` itself, but I don't think the entire implementation would have to follow the same license - though I may be wrong.

**Comment by Fabian-Gruenbichler** [comment]
zstd.h has Yann Collet listed as copyright holder as well, so it's probably prudent to reproduce that notice ;)

for Debian (where this popped up in review of the first upload which got rejected), I strip the pre-generated bindings and always use bindgen against the lib provided by the system/package repositories. prominently displaying that the bindings are mostly directly derived from BSD-3-clause licensed code is the right thing for sure. your PR has other unrelated changes as well I think?

IMHO the API describing comments copied to zstd-safe are also part of the source code, and thus covered by the original license. if you want to include them in zstd-safe, I think you'd need to license accordingly. it's probably also an option to just state which parts are copied and covered by BSD-3-clause.

note that modulo the "you need written permission to use Facebook or the names of the contributors to promote/endorse" BSD-3-clause and MIT are effectively identical, and both require attribution while allowing pretty much everything else. so it should be possible to mix them both even in single source files, provided all required attributions/notices are in place. I am not a lawyer (license or otherwise) though ;)

**Comment by infinity0** [comment]
I don't think you can just silently drop the GPL when documenting the license of the comments.

"At your choice" refers to the terms you choose when *distributing this* or otherwise doing something the license allows you to do that would normally be prohibited by copyright. It doesn't mean you can say the comments themselves are "not GPL" which is what you seem to be suggesting.

Note that you don't have to include the GPL text verbatim, just link to it.

**Comment by gyscos** [comment]
> zstd.h has Yann Collet listed as copyright holder as well, so it's probably prudent to reproduce that notice ;)

I'm just embedding the `LICENSE` file because it's easy, not sure why Yann is not mentionned there. :(

> prominently displaying that the bindings are mostly directly derived from BSD-3-clause licensed code is the right thing for sure. your PR has other unrelated changes as well I think?

Ah right, some re-formatting stuff that I'll pull in a separate PR.

On `zstd-safe`, I feel like removing the comments and linking to the online documentation at http://facebook.github.io/zstd/zstd_manual.html, but I wish there were more anchors to link to a specific function/type rather than just a chapter.

**Comment by anp** [comment]
> On zstd-safe, I feel like removing the comments

Did this end up happening? We're reviewing the crate for Fuchsia and would need to either have the comments removed or to have the BSD3 license acknowledged in the crate and top-level files.

**Comment by gyscos** [comment]
Yes, the zstd-safe crate currently does not contain any copied comment from the C library.

**Comment by stoneeric** [comment]
One other possible licensing concern came up around the use of generated text at github.com/gyscos/zstd-rs/blob/master/src/block/mod.rs#L62 - hipsum.co doesn't appear to define licensing terms around its generated text and we're not sure yet if it's copyrightable. 

A possible solution is to swap the text out with something handwritten (under the crate's license) or something clearly in the public domain. Would there be any concerns with this approach? I can provide a PR if you'd like.

**Comment by gyscos** [comment]
Ow, did not thing about that.
I started [a branch using a public domain text](https://github.com/gyscos/zstd-rs/tree/assets-public-domain) (in this case the jabberwocky poem). Would that be better?

**Comment by stoneeric** [comment]
Yeah, I think the lorem ipsum is probably fine, but avoiding ambiguity with Jabberwocky would be great. 

I see in the branch that [this test's text](https://github.com/gyscos/zstd-rs/blob/bc8cd3332a292bd4f9d4b2906b587474ee8e74ac/src/block/mod.rs#L62) hasn't been updated either, which is the more concerning piece. Would you mind handling that as well? (the comment indicates hipsum.co, did it come from somewhere else?)

Thanks for being responsive and willing to help out on this!

**Comment by gyscos** [comment]
Ha ha I must have glanced over the comment and assumed tlit was about the asset, as I don't even remember about this. Will replace it as well.

**Comment by gyscos** [comment]
The assets have been replaced.
Closing for now as all outstanding issues have been addressed, feel free to re-open if new a item comes up.
