### ISSUE TITLE
Update Zstandard to v1.4.5

### ISSUE THREAD

**Issue by Paoda** [gyscos/zstd-rs#86]
[zstd 1.4.5](https://github.com/facebook/zstd/releases/tag/v1.4.5) was released today. It boasts some speed improvements which would be nice to have at some point in the near future.

**Comment by repi** [comment]
Looks like it has been added now in https://github.com/gyscos/zstd-rs/commit/0be78635723e9fe2dce6556455309ab240956925

**Comment by Paoda** [comment]
Awesome! Closing.
