### ISSUE TITLE
dependencies are out of date

### ISSUE THREAD

**Issue by akiradeveloper** [gyscos/zstd-rs#96]
Hi, can you afford maintaining this library?

The dependencies on tokio and futures are on the older versions.

```
tokio-io = { version = "0.1", optional = true }
futures = { version = "0.1", optional = true }
```

tokio's recently released 0.3 and futures is now 0.3. These versions are way too old.

**Comment by gyscos** [comment]
Hi - I am not very familiar with the async ecosystem yet - I barely wrote the current `tokio_io` implementation of `AsyncWrite`, but at a glance the current `tokio::io::AsyncWrite` requires more effort.

If you are more familiar with it and are willing to send a PR, I would be glad to review it.

**Comment by gyscos** [comment]
[async-compression](https://github.com/Nemo157/async-compression) seems to have nice re-usable async wrappers around a bunch of compression libs, including zstd-rs. I am tempted to simply remove all tokio/futures support code from here, and instead point to that crate for people needing an async version.

They only use `zstd::stream::raw`, basically re-implementing an async version of the `zstd::stream::zio` module generically for a bunch of compression libraries.

**Comment by gyscos** [comment]
No more tokio code in-tree.
